import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import PlayersList from "@/components/pages/players/PlayersList";
import PlayerDialog from "@/components/pages/players/PlayerDialog";
import PlayerRegulations from "@/components/pages/players/PlayerRegulations";
import { usePlayersUpdated } from "@/components/pages/players/usePlayersUpdated";
import { usePlayerListLock } from "@/components/user/players/hooks/usePlayerListLock";
import { useAuth } from "@/components/auth/AuthProvider";
import { formatDateShort } from "@/lib/dateUtils"; 