import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import PlayersList from "@/components/pages/admin/players/components/PlayersList";
import PlayerRegulations from "@/components/pages/admin/players/components/PlayerRegulations";
import { usePlayersUpdated } from "@/components/pages/admin/players/hooks/usePlayersUpdated";
import { usePlayerListLock } from "@/components/pages/admin/players/hooks/usePlayerListLock";
import { useAuth } from "@/hooks/useAuth";
import { formatDateShort } from "@/lib/dateUtils";
import { PlayerModal } from "@/components/modals";