-- Optimize referee poll system using existing structure

-- Add columns to existing matches table for poll grouping and referee assignment
ALTER TABLE public.matches 
ADD COLUMN poll_group_id varchar(50),
ADD COLUMN assigned_referee_id integer,
ADD COLUMN poll_month varchar(7); -- Format: YYYY-MM

-- Create index for efficient querying
CREATE INDEX idx_matches_poll_group ON public.matches(poll_group_id);
CREATE INDEX idx_matches_poll_month ON public.matches(poll_month);
CREATE INDEX idx_matches_assigned_referee ON public.matches(assigned_referee_id);

-- Only need one new table for referee availability (many-to-many relationship)
CREATE TABLE public.referee_availability (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    poll_group_id varchar(50) NOT NULL,
    poll_month varchar(7) NOT NULL,
    is_available boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(user_id, poll_group_id, poll_month)
);

-- Enable RLS
ALTER TABLE public.referee_availability ENABLE ROW LEVEL SECURITY;

-- RLS policies for referee_availability
CREATE POLICY "Admins can manage all referee availability" 
ON public.referee_availability FOR ALL 
USING (get_current_user_role() = 'admin')
WITH CHECK (get_current_user_role() = 'admin');

CREATE POLICY "Referees can manage their own availability" 
ON public.referee_availability FOR ALL 
USING (user_id = (current_setting('app.current_user_id', true))::integer)
WITH CHECK (user_id = (current_setting('app.current_user_id', true))::integer);

-- Use application_settings for polls and notifications
-- Poll settings will use category 'referee_polls' with setting_name as month (YYYY-MM)
-- Notification settings will use category 'admin_notifications' 

-- Add application setting to control referee poll visibility
INSERT INTO public.application_settings (setting_category, setting_name, setting_value, is_active)
VALUES ('referee_polls', 'system_enabled', '{"enabled": false}'::jsonb, true)
ON CONFLICT (setting_category, setting_name) DO NOTHING;