// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuyviionmstyvkvglizh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1eXZpaW9ubXN0eXZrdmdsaXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDc3NDQsImV4cCI6MjA2MjIyMzc0NH0.a8pkewpTbzFsLptp_yWD98tHgBlFXKHCRP_Bh3D2XYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);